### ISSUE TITLE
wallhaven.cc is out of alpha

### ISSUE THREAD

**Issue by Pertelectrical** [patricker/Pulse#1]
hi 
i  hope you are doing well
wallhaven.cc is now out of alpha so please update pulse :D

**Comment by alaa777** [comment]
+1

**Comment by patricker** [comment]
@Pertelectrical / @alaa777 Wow, It actually means a lot that you guys came and asked for this after all these years.

I'll look into this.  Maybe we can have a release of Pulse after so many years.

**Comment by alaa777** [comment]
wow thank you so much 
your app is the best wallpaper app i have ever used

**Comment by patricker** [comment]
I have a working alpha with Wallhaven working. The developers were _really_ kind and included a honest to goodness API for people like me to call.  Let me get it into a beta level stability wise and I'll post a link to a build here.

**Comment by alaa777** [comment]
Great thank you so much :D

**Comment by patricker** [comment]
Here is a beta. I dropped the other providers for now, as they need some testing after all these years.
https://www.dropbox.com/s/amcti27l4w3imv1/Pulse.zip?dl=0

Remember that sometimes Windows Blocks exe's downloaded from the internet zip files, I used to have a wiki article on CodePlex. Right click the zip file after downloading and check for an `Unblock` button before unzipping.

**Comment by alaa777** [comment]
Ok great thanks i will tray it and report any issues :D

**Comment by alaa777** [comment]
i got this error after i added my api key 

> 8/17/2019 4:39:00 PM -- Errors -- Unhandled exception! Error Details: System.NullReferenceException: Object reference not set to an instance of an object.
   at Pulse.Base.PictureManager.<>c__DisplayClass14_0.<GetPictureList>b__0(Picture x) in C:\Code\Pulse\Pulse\Pulse.Base\Pictures\PictureManager.cs:line 307
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Pulse.Base.PictureManager.GetPictureList(PictureSearch ps) in C:\Code\Pulse\Pulse\Pulse.Base\Pictures\PictureManager.cs:line 307
   at Pulse.Base.PulseRunner.DownloadNextPicture() in C:\Code\Pulse\Pulse\Pulse.Base\PulseRunner.cs:line 238
   at Pulse.Base.PulseRunner.<SkipToNextPicture>b__36_0() in C:\Code\Pulse\Pulse\Pulse.Base\PulseRunner.cs:line 171
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
8/17/2019 4:39:41 PM -- Errors -- Error downloading picture object from 'System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.List`1.Add(T item)
   at wallhaven.Provider.<>c__DisplayClass6_0.<FetchPictures>b__0(Picture p) in C:\Code\Pulse\Pulse\Providers\wallbase\Provider.cs:line 108'. Exception details: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.List`1.Add(T item)
   at wallhaven.Provider.<>c__DisplayClass6_0.<FetchPictures>b__0(Picture p) in C:\Code\Pulse\Pulse\Providers\wallbase\Provider.cs:line 108
8/17/2019 4:39:41 PM -- Errors -- Error downloading picture object from 'System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.List`1.Add(T item)
   at wallhaven.Provider.<>c__DisplayClass6_0.<FetchPictures>b__0(Picture p) in C:\Code\Pulse\Pulse\Providers\wallbase\Provider.cs:line 119'. Exception details: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.List`1.Add(T item)
   at wallhaven.Provider.<>c__DisplayClass6_0.<FetchPictures>b__0(Picture p) in C:\Code\Pulse\Pulse\Providers\wallbase\Provider.cs:line 119
8/17/2019 4:39:41 PM -- Errors -- Unhandled exception! Error Details: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.<TakeIterator>d__25`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at wallhaven.Provider.GetPictures(PictureSearch ps) in C:\Code\Pulse\Pulse\Providers\wallbase\Provider.cs:line 92
   at Pulse.Base.PictureManager.GetPictureList(PictureSearch ps) in C:\Code\Pulse\Pulse\Pulse.Base\Pictures\PictureManager.cs:line 298
   at Pulse.Base.PulseRunner.DownloadNextPicture() in C:\Code\Pulse\Pulse\Pulse.Base\PulseRunner.cs:line 238
   at Pulse.Base.PulseRunner.<SkipToNextPicture>b__36_0() in C:\Code\Pulse\Pulse\Pulse.Base\PulseRunner.cs:line 171
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by patricker** [comment]
What were your search settings?  I don't know if I've tested api key beyond NSFW searches. I don't think I've implemented favorite/collection...

**Comment by Pertelectrical** [comment]
same i got this error

[Pulse_20190818.txt](https://github.com/patricker/Pulse/files/3512736/Pulse_20190818.txt)

![1](https://user-images.githubusercontent.com/53853738/63221030-7182cd00-c19b-11e9-9fa9-2a97124670c9.PNG)
![2](https://user-images.githubusercontent.com/53853738/63221031-7182cd00-c19b-11e9-88aa-14649de01f04.PNG)
![3](https://user-images.githubusercontent.com/53853738/63221032-721b6380-c19b-11e9-9fc3-b6c6d7e163b4.PNG)

**Comment by alaa777** [comment]
i noticed i get the error when i change the resolution of the image size
![1](https://user-images.githubusercontent.com/29731219/63225285-c859c800-c1d6-11e9-8c30-e02b00d054c2.jpg)

**Comment by alaa777** [comment]
yes 100% when i change the resolution

**Comment by patricker** [comment]
As a quick test, can you disable "Check for new versions on startup"? @Pertelectrical, I see in your log that it's failing because Codeplex basically doesn't exist anymore, and the code is still checking Codeplex for a new version... I'll take that out in the next version.

@alaa777 Are you setting "Image Size" to blank, or just clearing out the resolution? I found a bug yesterday where setting Image Size to blank would cause a crash, and have fixed it in my local code.

**Comment by alaa777** [comment]
not to blank when i change it to match my laptop resolution with the "at least " option

**Comment by alaa777** [comment]
any updates?

**Comment by Pertelectrical** [comment]
you are done with this project for good?
just to stop checking i have been checking for years XD

**Comment by patricker** [comment]
@Pertelectrical no, not at all. I'm working on changes based on feedback, but I have limited free time to work on Pulse. (Full time job/family)  I will post another beta soon.

**Comment by Pertelectrical** [comment]
yeah i understand just checking and thanks :D

**Comment by Pertelectrical** [comment]
currently its working with the default setting any changes makes it unstable 
and some times it just stops working and after restarting it 3 or 4 times it start working again

**Comment by alaa777** [comment]
Same

**Comment by alaa777** [comment]
some how it just stopped working "not downloading any new wallpapers"

**Comment by patricker** [comment]
@alaa777 In the Pulse directory there is a log folder.  Do you see any errors in the latest log file?  If you are comfortable uploading the log file, that would be helpful too.

**Comment by alaa777** [comment]
[Pulse_20200204.txt](https://github.com/patricker/Pulse/files/4189696/Pulse_20200204.txt)
this is the latest one but this bug is not triggering an exception its just no images being downloaded 
i will try change the setting maybe there are no images that match the setting but i doubt  it since i haven't change the settings since its started working

**Comment by alaa777** [comment]
[CACHE_-1464680403_wallhaven.Provider.zip](https://github.com/patricker/Pulse/files/4189713/CACHE_-1464680403_wallhaven.Provider.zip)

**Comment by alaa777** [comment]
i deleted everything and i cant get it to work again help please 
[New Text Document.txt](https://github.com/patricker/Pulse/files/4210209/New.Text.Document.txt)

**Comment by patricker** [comment]
@alaa777 Thanks for your help in testing these changes.  It's working for me, but I think my version has some changes.  I've zipped up a fresh build: https://www.dropbox.com/s/amcti27l4w3imv1/Pulse.zip?dl=0

**Comment by alaa777** [comment]
thank you so much :D

**Comment by alaa777** [comment]
Exact same error
[error.txt](https://github.com/patricker/Pulse/files/4234232/error.txt)

**Comment by alaa777** [comment]
another one
[error2.txt](https://github.com/patricker/Pulse/files/4234235/error2.txt)

**Comment by patricker** [comment]
With the zip I sent you, here is how I tested it:

1. Launch `pulse.exe`
2. Opened `Options`
3. Clicked the `Add` button next to `Wallhaven`
4. Clicked `Save`, wallpaper downloaded and was set on my desktop.

Can you restart from scratch and see if this basic test works?

**Comment by alaa777** [comment]
i can't because the error keeps interrupting me i keep clicking continue but the error message just appears again

**Comment by alaa777** [comment]
[not working.zip](https://github.com/patricker/Pulse/files/4234564/not.working.zip)

**Comment by patricker** [comment]
@alaa777 I remember maybe Windows was blocking the zip last time?

> Remember that sometimes Windows Blocks exe's downloaded from the internet zip files, I used to have a wiki article on CodePlex. Right click the zip file after downloading and check for an Unblock button before unzipping.

Pictures: https://singularlabs.com/tips/how-to-unblock-a-zip-file-on-windows-10/

See if this is relevant.

**Comment by alaa777** [comment]
Lol wtf i never knew that was a thing at all sry i said wtf but that is so strange lol it worked XD
thanks

**Comment by alaa777** [comment]
i got this error but it works fine when i restart it
![Annotation 2020-03-01 072225](https://user-images.githubusercontent.com/29731219/75619499-936afc80-5b8d-11ea-8e94-bbbf9cbcac18.jpg)
[Pulse_20200301.txt](https://github.com/patricker/Pulse/files/4271341/Pulse_20200301.txt)

**Comment by alaa777** [comment]
i got this error again during windows startup but its working fine after relaunching the app
[Pulse_20200426.txt](https://github.com/patricker/Pulse/files/4534502/Pulse_20200426.txt)
